# Generated by Django 2.2.3 on 2019-07-22 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objectsensormapping',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('objectname', models.CharField(blank=True, max_length=50, null=True)),
                ('workflowid', models.IntegerField(blank=True, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('objectimagepath', models.CharField(blank=True, max_length=100, null=True)),
                ('activerecord', models.CharField(blank=True, max_length=1, null=True)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('updateddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'objectsensormapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Objecttransaction',
            fields=[
                ('transactionid', models.BigAutoField(primary_key=True, serialize=False)),
                ('sensorname', models.CharField(blank=True, max_length=50, null=True)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('objectname', models.CharField(blank=True, max_length=50, null=True)),
                ('param1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('param2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('param3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('param4', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('param5', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('batterylevel', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('rssi', models.SmallIntegerField(blank=True, null=True)),
                ('sensorid', models.CharField(blank=True, max_length=20, null=True)),
                ('zoneid', models.CharField(blank=True, max_length=20, null=True)),
                ('param6', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('entrydatetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'objecttransaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensormaster',
            fields=[
                ('sensorid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sensorname', models.CharField(blank=True, max_length=50, null=True)),
                ('sensortypeid', models.IntegerField(blank=True, null=True)),
                ('paramtype1', models.CharField(blank=True, max_length=20, null=True)),
                ('paramtype2', models.CharField(blank=True, max_length=20, null=True)),
                ('paramtype3', models.CharField(blank=True, max_length=20, null=True)),
                ('paramtype4', models.CharField(blank=True, max_length=20, null=True)),
                ('paramtype5', models.CharField(blank=True, max_length=20, null=True)),
                ('activesensor', models.CharField(blank=True, max_length=1, null=True)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('updateddate', models.DateTimeField(blank=True, null=True)),
                ('paramtype6', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sensormaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensortypemaster',
            fields=[
                ('sensortypeid', models.AutoField(primary_key=True, serialize=False)),
                ('sensortypename', models.CharField(blank=True, max_length=50, null=True)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('updateddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sensortypemaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zonemaster',
            fields=[
                ('zoneid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('zonename', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('zoneimagepath', models.CharField(blank=True, max_length=100, null=True)),
                ('activezone', models.CharField(blank=True, max_length=1, null=True)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('updateddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zonemaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companymaster',
            fields=[
                ('companyid', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(blank=True, max_length=100, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=25, null=True)),
                ('mobilenumber', models.CharField(blank=True, max_length=25, null=True)),
                ('emailid', models.CharField(blank=True, max_length=25, null=True)),
                ('contactperson', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('permittedobjects', models.IntegerField(blank=True, null=True)),
                ('permittedzones', models.IntegerField(blank=True, null=True)),
                ('subscriptionstartdate', models.DateField(blank=True, null=True)),
                ('subscriptionenddate', models.DateField(blank=True, null=True)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('updateddate', models.DateTimeField(blank=True, null=True)),
                ('activecompany', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'companymaster',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Objectzonedetails',
            fields=[
                ('objectid', models.ForeignKey(db_column='objectid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='remote.Objectsensormapping')),
                ('objectname', models.CharField(blank=True, max_length=50, null=True)),
                ('zoneid', models.CharField(blank=True, max_length=20, null=True)),
                ('zonename', models.CharField(blank=True, max_length=50, null=True)),
                ('updateddatetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'objectzonedetails',
                'managed': False,
            },
        ),
    ]
